apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  selector:
   # app: kafka-cluster
    pod-name: crs-kafka-0
    pod-name: crs-kafka1-0
    pod-name: crs-kafka2-0
  ports:
  - port: 9092
    targetPort: 9092
  type: LoadBalancer
