apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-kafka1
spec:
  replicas: 1
  serviceName: kafka-cluster
  selector:
    matchLabels:
        app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: bitnami/kafka:2.6.0  
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "0.2"             
        ports:
         - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: crs-zookeeper-0.zookeeper-cluster.kafka.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.kafka.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.kafka.svc.cluster.local:218
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes" 
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(MY_POD_IP):9092
        volumeMounts:
        - name: kafka-mount
          mountPath: /bitnami/kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-mount
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
