apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
metadata:
  name: crs-kafka
spec:
  replicas: 3
  serviceName: kafka-cluster
  selector:
    matchLabels:
        app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: bitnami/kafka:2.6.0  
#        image: bitnami/kafka:latest
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "0.3"             
        ports:
         - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.default.svc.cluster.local:2181
#          value: zookeeper-cluster:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes" 
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes" 
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
          #value: LISTENER_PUBLIC://34.170.117.132:32742,LISTENER_INTERNAL://10.8.9.53:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://10.4.1.40:9092,PLAINTEXT://10.4.1.41:9092,PLAINTEXT://10.4.1.42:9092
      #  - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
       #   value: PLAINTEXT:PLAINTEXT 
        #- name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
         # value: LISTENER_PUBLIC
